# Generated by Django 4.1.7 on 2023-03-24 19:56

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=255, populate_from='name', unique=True),
        ),
    ]
