# Generated by Django 4.1.7 on 2023-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='attempts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guess',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
    ]
